set_known_position:
  fields:
    entity_id:
      example: cover.blinds
    position:
      example: 50
set_known_tilt_position:
  fields:
    entity_id:
      example: cover.blinds
    position:
      example: 50
start_calibration:
  fields:
    entity_id:
      example: cover.blinds
    attribute:
      example: travel_time_down
    timeout:
      example: 120
stop_calibration:
  fields:
    entity_id:
      example: cover.blinds
    cancel:
      example: false
