set_known_position:
  target:
    entity:
      domain: cover
      integration: cover_time_based
  fields:
    position:
      required: true
      example: 50
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"

set_known_tilt_position:
  target:
    entity:
      domain: cover
      integration: cover_time_based
  fields:
    tilt_position:
      required: true
      example: 50
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"

start_calibration:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: cover
          integration: cover_time_based
    attribute:
      required: true
      example: travel_time_down
      selector:
        select:
          options:
            - travel_time_down
            - travel_time_up
            - tilt_time_down
            - tilt_time_up
            - travel_motor_overhead
            - tilt_motor_overhead
            - min_movement_time
    timeout:
      required: true
      example: 120
      default: 120
      selector:
        number:
          min: 1
          max: 600
          step: 1
          unit_of_measurement: "s"
    direction:
      required: false
      selector:
        select:
          options:
            - open
            - close

stop_calibration:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: cover
          integration: cover_time_based
    cancel:
      required: false
      default: false
      selector:
        boolean:
